### ISSUE TITLE
Links to Zenika Resume no longer work

### ISSUE THREAD

**Issue by hgwood** [Zenika/Zenika-Resume-Analysis#1]
Cliquer sur le bouton "Voir CV" n'emmène plus vers le bon endroit sur Zenika Resume.

**Comment by ClementVanPeuter** [comment]
Etat des lieux de mon coté:

Pour set un env dev en local.

En ne touchant à rien (dans les fichiers d'environnements).

```
npm run dev
```
![capture d ecran_2018-10-10_13-58-27](https://user-images.githubusercontent.com/42938784/46734806-94e40e00-cc94-11e8-8f78-78b9fbd7ffed.png)

En touchant environment.ts:
```
export const environment = {
  production: false,
  backendApi:'http://localhost:4200'
};

```
L'app part dans une boucle d'authentification.

En touchant environment.ts pour setter le back sur celui de la prod:
```
export const environment = {
  production: false,
  backendApi:'https://zenika-search-resume-backend.herokuapp.com'
};

```
![capture d ecran_2018-10-10_14-01-37](https://user-images.githubusercontent.com/42938784/46734957-058b2a80-cc95-11e8-9428-c787ec4ee709.png)
